#!/bin/bash
INSTANCE=${1}
TENSORBOARD=${2}
echo ${TENSORBOARD}" from "${INSTANCE}
scp -r -i "/Users/david/Documents/amazonws/ubuntu/autohandleubuntu-12-64.pem" ubuntu@${INSTANCE}":"'./CarND-Semantic-Segmentation/runs/'${TENSORBOARD} ./runs
