#!/bin/bash
INSTANCE=${1}
scp -i "/Users/david/Documents/amazonws/ubuntu/autohandleubuntu-12-64.pem" ubuntu@${INSTANCE}":"'jeremyshannon/CarND-Semantic-Segmentation/runs/1519686240.8257887/*_000000.png' runs
